### ISSUE TITLE
Exception when consuming unknown field with value being empty list

### ISSUE THREAD

**Issue by kskalski** [bivas/protobuf-java-format#40]
parsing something like
{
   "unknown": []
}

fails with
com.googlecode.protobuf.format.JsonFormat$ParseException: 1:32: Expected string.
        at com.googlecode.protobuf.format.JsonFormat$Tokenizer.parseException(JsonFormat.java:734)
        at com.googlecode.protobuf.format.JsonFormat$Tokenizer.consumeString(JsonFormat.java:683)
        at com.googlecode.protobuf.format.JsonFormat.handleMissingField(JsonFormat.java:909)
        at com.googlecode.protobuf.format.JsonFormat.handleMissingField(JsonFormat.java:895)
        at com.googlecode.protobuf.format.JsonFormat.mergeField(JsonFormat.java:853)
        at com.googlecode.protobuf.format.JsonFormat.mergeField(JsonFormat.java:875)
        at com.googlecode.protobuf.format.JsonFormat.merge(JsonFormat.java:790)

**Comment by kskalski** [comment]
Looks like last branch in handleMissingField (https://github.com/bivas/protobuf-java-format/blob/master/src/main/java/com/googlecode/protobuf/format/JsonFormat.java#L908) should check if tokenizer.currentToken() starts with ' or " instead of blindly calling consumeString

**Comment by bivas** [comment]
Can you please prepare a test and PR?

**Comment by kskalski** [comment]
https://github.com/bivas/protobuf-java-format/pull/41

**Comment by bivas** [comment]
Merged #41
